hostname: Edge11
ip_routing: true
spanning_tree:
  mode: mstp
loopback_interfaces:
- name: Loopback0
  description: Edge-11_lo0
  shutdown: false
  ip_address: 192.168.0.11/32
ethernet_interfaces:
- name: Ethernet1
  peer: Edge11
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet2
  peer: Edge11
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet3
  peer: Leaf11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.11.31.1/24
- name: Ethernet4
  peer: R1-PE1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.11.15.1/24
- name: Ethernet5
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.11.16.1/24
- name: Ethernet6
  peer: Leaf12
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.11.32.1/24
router_bgp:
  as: 65000
  router_id: 192.168.0.11
  neighbors:
    - ip_address: 192.11.15.2
      remote_as:  65000
    - ip_address: 192.11.16.2
      remote_as:  65000
    - ip_address: 192.11.31.2
      remote_as:  65000
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.11/32
  redistribute_routes:
    - source_protocol: connected