hostname: Edge12
ip_routing: true
spanning_tree:
  mode: mstp
loopback_interfaces:
- name: Loopback0
  description: Edge-12_lo0
  shutdown: false
  ip_address: 192.168.0.12/32
ethernet_interfaces:
- name: Ethernet1
  peer: Edge12
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.12.32.1/24
- name: Ethernet2
  peer: Edge11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.15.1/24
- name: Ethernet3
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.16.1/24
- name: Ethernet4
  peer: Leaf11
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.12.31.1/24
router_bgp:
  as: 65000
  router_id: 192.168.0.12
  neighbors:
    - ip_address: 192.12.15.2
      remote_as:  65000
    - ip_address: 192.12.16.2
      remote_as:  65000
    - ip_address: 192.12.32.2
      remote_as:  65000
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.12/32
  redistribute_routes:
    - source_protocol: connected