hostname: Edge20
ip_routing: true
spanning_tree:
  mode: mstp
loopback_interfaces:
- name: Loopback0
  description: Edge-20_lo0
  shutdown: false
  ip_address: 192.168.0.20/32
ethernet_interfaces:
- name: Ethernet1
  peer: Edge20
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet2
  peer: Edge20
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet3
  peer: Leaf21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.20.33.1/24
- name: Ethernet4
  peer: R2-PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.20.25.1/24
- name: Ethernet5
  peer: ISP-2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.20.26.1/24
router_bgp:
  as: 65220
  router_id: 192.168.0.20
  neighbors:
    - ip_address: 192.20.25.2
      remote_as:  65202
    - ip_address: 192.20.26.2
      remote_as:  65203
    - ip_address: 192.20.33.2
      remote_as:  65220
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.20/32