hostname: Leaf11
ip_routing: true
spanning_tree:
  mode: mstp
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
- name: Loopback0
  description: Leaf11_lo0
  shutdown: false
  ip_address: 192.168.0.31/32
ethernet_interfaces:
- name: Ethernet1
  peer: H111
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.11.254/24
  vrf: VRF_A
- name: Ethernet2
  peer: Edge10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.10.31.2/24
- name: Ethernet3
  peer: Edge11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.11.31.2/24
- name: Ethernet4
  peer: Edge22
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.12.31.2/24
router_bgp:
  as: 65000
  router_id: 192.168.0.31
  neighbors:
    - ip_address: 192.10.31.1
      remote_as:  65000
    - ip_address: 192.11.31.1
      remote_as:  65000
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.31/32
