hostname: P10
ip_routing: true
spanning_tree:
  mode: mstp
loopback_interfaces:
- name: Loopback0
  description: Region1_P10_lo0
  shutdown: false
  ip_address: 192.168.0.51/32
ethernet_interfaces:
- name: Ethernet1
  peer: P11
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.51.52.1/24
- name: Ethernet2
  peer: R1-PE1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.15.51.2/24
- name: Ethernet3
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.16.51.2/24
- name: Ethernet4
  peer: PE1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.51.81.1/24
- name: Ethernet5
  peer: PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.51.82.1/24
- name: Ethernet6
  peer: ISP-3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.51.75.1/24
- name: Ethernet7
  peer: Edge14
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.14.51.2/24
router_bgp:
  as: 65000
  router_id: 51.51.51.51
  peer_groups:
    - name: CORE
      remote_as: 65001
    - name: ISP-3
      remote_as: 65002
  neighbors:
    - ip_address: 192.51.81.2
      peer_group: CORE
    - ip_address: 192.51.82.2
      peer_group: CORE
    - ip_address: 192.51.75.2
      peer_group: ISP-3
    - ip_address: 192.15.51.1
      remote_as:  65102
    - ip_address: 192.16.51.1
      remote_as:  65103
  address_family_ipv4:
    networks:
      - prefix: 192.168.0.51/32
      - prefix: 51.51.51.51/32
    redistribute_routes:
      - source_protocol: connected
