custom_hostname: PE3
custom_router_isis:
  instance: CORE
  segment_routing_mpls:
    enabled: true
    router_id: 192.168.0.101.23
  eos_cli: |-
    traffic-engineering
      no shutdown
      is-type level-1
custom_router_traffic_engineering:
  #enabled: true
  segment_routing:
  router_id:
    ipv4: 192.168.101.23