hostname: RR1
ip_routing: true
spanning_tree:
  mode: mstp
loopback_interfaces:
- name: Loopback0
  description: RR1_lo0
  shutdown: false
  ip_address: 192.168.0.71/32
ethernet_interfaces:
  - name: Ethernet1
    peer: RR2
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 192.71.72.2/24
  - name: Ethernet2
    peer: R1-PE1
    type: routed
    shutdown: true
    mtu: 1500
    ip_address: 192.15.71.2/24
  - name: Ethernet3
    peer: ISP-1
    type: routed
    shutdown: true
    mtu: 1500
    ip_address: 192.16.71.2/24
router_bgp:
  as: 65000
  router_id: 192.168.0.71
  neighbors:
    - ip_address: 192.15.71.1
      remote_as:  65000
    - ip_address: 192.16.71.1
      remote_as:  65000
  address_family_ipv4:
    networks: 
      - prefix: 192.168.0.71/32